/* eslint-disable sort-keys */
export const formFields = [
  {
    fieldDefault: "",
    fieldFlags: "0",
    fieldMaxLength: "",
    fieldOptions: ["1", "Off"],
    fieldType: "Button",
    fieldValue: "Off",
    title: "topmostSubform[0].Page1[0].FilingStatus[0].c1_01[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "0",
    fieldMaxLength: "",
    fieldOptions: ["2", "Off"],
    fieldType: "Button",
    fieldValue: "Off",
    title: "topmostSubform[0].Page1[0].FilingStatus[0].c1_01[1]",
  },
  {
    fieldDefault: "",
    fieldFlags: "0",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Button",
    fieldValue: "Off",
    title: "topmostSubform[0].Page1[0].FilingStatus[0].c1_01[2]",
  },
  {
    fieldDefault: "",
    fieldFlags: "0",
    fieldMaxLength: "",
    fieldOptions: ["4", "Off"],
    fieldType: "Button",
    fieldValue: "Off",
    title: "topmostSubform[0].Page1[0].FilingStatus[0].c1_01[3]",
  },
  {
    fieldDefault: "",
    fieldFlags: "0",
    fieldMaxLength: "",
    fieldOptions: ["5", "Off"],
    fieldType: "Button",
    fieldValue: "Off",
    title: "topmostSubform[0].Page1[0].FilingStatus[0].c1_01[4]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page1[0].FilingStatus[0].f1_01[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page1[0].f1_02[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page1[0].f1_03[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "25165824",
    fieldMaxLength: "9",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page1[0].YourSocial[0].f1_04[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page1[0].f1_05[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page1[0].f1_06[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "25165824",
    fieldMaxLength: "9",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page1[0].SpousesSocial[0].f1_07[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page1[0].Address[0].f1_08[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page1[0].Address[0].f1_09[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page1[0].Address[0].f1_10[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page1[0].Address[0].f1_11[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page1[0].Address[0].f1_12[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page1[0].Address[0].f1_13[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page1[0].Address[0].f1_14[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page1[0].Address[0].f1_15[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "0",
    fieldMaxLength: "",
    fieldOptions: ["1", "Off"],
    fieldType: "Button",
    fieldValue: "Off",
    title: "topmostSubform[0].Page1[0].c1_02[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "0",
    fieldMaxLength: "",
    fieldOptions: ["1", "Off"],
    fieldType: "Button",
    fieldValue: "Off",
    title: "topmostSubform[0].Page1[0].c1_03[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "0",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Button",
    fieldValue: "Off",
    title: "topmostSubform[0].Page1[0].c1_04[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "0",
    fieldMaxLength: "",
    fieldOptions: ["2", "Off"],
    fieldType: "Button",
    fieldValue: "Off",
    title: "topmostSubform[0].Page1[0].c1_04[1]",
  },
  {
    fieldDefault: "",
    fieldFlags: "0",
    fieldMaxLength: "",
    fieldOptions: ["1", "Off"],
    fieldType: "Button",
    fieldValue: "Off",
    title: "topmostSubform[0].Page1[0].c1_05[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "0",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Button",
    fieldValue: "Off",
    title: "topmostSubform[0].Page1[0].c1_06[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "0",
    fieldMaxLength: "",
    fieldOptions: ["1", "Off"],
    fieldType: "Button",
    fieldValue: "Off",
    title: "topmostSubform[0].Page1[0].c1_07[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "0",
    fieldMaxLength: "",
    fieldOptions: ["1", "Off"],
    fieldType: "Button",
    fieldValue: "Off",
    title: "topmostSubform[0].Page1[0].c1_08[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "0",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Button",
    fieldValue: "Off",
    title: "topmostSubform[0].Page1[0].c1_09[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "0",
    fieldMaxLength: "",
    fieldOptions: ["1", "Off"],
    fieldType: "Button",
    fieldValue: "Off",
    title: "topmostSubform[0].Page1[0].c1_10[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "0",
    fieldMaxLength: "",
    fieldOptions: ["1", "Off"],
    fieldType: "Button",
    fieldValue: "Off",
    title: "topmostSubform[0].Page1[0].c1_11[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "0",
    fieldMaxLength: "",
    fieldOptions: ["1", "Off"],
    fieldType: "Button",
    fieldValue: "Off",
    title: "topmostSubform[0].Page1[0].Dependents_ReadOrder[0].c1_12[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title:
      "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow1[0].f1_16[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "16777216",
    fieldMaxLength: "9",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title:
      "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow1[0].f1_17[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title:
      "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow1[0].f1_18[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "0",
    fieldMaxLength: "",
    fieldOptions: ["1", "Off"],
    fieldType: "Button",
    fieldValue: "Off",
    title:
      "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow1[0].c1_13[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "0",
    fieldMaxLength: "",
    fieldOptions: ["1", "Off"],
    fieldType: "Button",
    fieldValue: "Off",
    title:
      "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow1[0].c1_14[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title:
      "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow2[0].f1_19[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "16777216",
    fieldMaxLength: "9",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title:
      "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow2[0].f1_20[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title:
      "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow2[0].f1_21[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "0",
    fieldMaxLength: "",
    fieldOptions: ["1", "Off"],
    fieldType: "Button",
    fieldValue: "Off",
    title:
      "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow2[0].c1_15[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "0",
    fieldMaxLength: "",
    fieldOptions: ["1", "Off"],
    fieldType: "Button",
    fieldValue: "Off",
    title:
      "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow2[0].c1_16[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title:
      "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow3[0].f1_22[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "16777216",
    fieldMaxLength: "9",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title:
      "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow3[0].f1_23[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title:
      "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow3[0].f1_24[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "0",
    fieldMaxLength: "",
    fieldOptions: ["1", "Off"],
    fieldType: "Button",
    fieldValue: "Off",
    title:
      "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow3[0].c1_17[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "0",
    fieldMaxLength: "",
    fieldOptions: ["1", "Off"],
    fieldType: "Button",
    fieldValue: "Off",
    title:
      "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow3[0].c1_18[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title:
      "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow4[0].f1_25[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "16777216",
    fieldMaxLength: "9",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title:
      "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow4[0].f1_26[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title:
      "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow4[0].f1_27[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "0",
    fieldMaxLength: "",
    fieldOptions: ["1", "Off"],
    fieldType: "Button",
    fieldValue: "Off",
    title:
      "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow4[0].c1_19[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "0",
    fieldMaxLength: "",
    fieldOptions: ["1", "Off"],
    fieldType: "Button",
    fieldValue: "Off",
    title:
      "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow4[0].c1_20[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_28[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_29[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_30[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_31[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_32[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_33[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_34[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_35[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_36[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_37[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_38[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "0",
    fieldMaxLength: "",
    fieldOptions: ["1", "Off"],
    fieldType: "Button",
    fieldValue: "Off",
    title: "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].c1_21[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_39[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_40[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_41[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title:
      "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].Line10-12_ReadOrder[0].f1_42[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title:
      "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].Line10-12_ReadOrder[0].f1_43[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_44[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_45[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page1[0].f1_46[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page1[0].f1_47[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page1[0].f1_48[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page1[0].f1_49[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "0",
    fieldMaxLength: "",
    fieldOptions: ["1", "Off"],
    fieldType: "Button",
    fieldValue: "Off",
    title: "topmostSubform[0].Page2[0].c2_01[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "0",
    fieldMaxLength: "",
    fieldOptions: ["1", "Off"],
    fieldType: "Button",
    fieldValue: "Off",
    title: "topmostSubform[0].Page2[0].c2_02[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "0",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Button",
    fieldValue: "Off",
    title: "topmostSubform[0].Page2[0].c2_03[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page2[0].f2_01[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page2[0].f2_02[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page2[0].f2_03[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page2[0].f2_04[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page2[0].f2_05[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page2[0].f2_06[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page2[0].f2_07[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page2[0].f2_08[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page2[0].f2_09[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page2[0].f2_10[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page2[0].Line25_ReadOrder[0].f2_11[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page2[0].Line25_ReadOrder[0].f2_12[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page2[0].Line25_ReadOrder[0].f2_13[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page2[0].Lines26-27_ReadOrder[0].f2_14[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page2[0].Lines26-27_ReadOrder[0].f2_15[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page2[0].Lines27-32_ReadOrder[0].f2_16[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page2[0].Lines27-32_ReadOrder[0].f2_17[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page2[0].Lines27-32_ReadOrder[0].f2_18[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page2[0].Lines27-32_ReadOrder[0].f2_19[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page2[0].Lines27-32_ReadOrder[0].f2_20[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page2[0].Line32-33_ReadOrder[0].f2_21[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page2[0].f2_22[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page2[0].f2_23[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "0",
    fieldMaxLength: "",
    fieldOptions: ["1", "Off"],
    fieldType: "Button",
    fieldValue: "Off",
    title: "topmostSubform[0].Page2[0].c2_04[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page2[0].f2_24[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "25165824",
    fieldMaxLength: "9",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page2[0].RoutingNo[0].f2_25[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "0",
    fieldMaxLength: "",
    fieldOptions: ["1", "Off"],
    fieldType: "Button",
    fieldValue: "Off",
    title: "topmostSubform[0].Page2[0].c2_05[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "0",
    fieldMaxLength: "",
    fieldOptions: ["2", "Off"],
    fieldType: "Button",
    fieldValue: "Off",
    title: "topmostSubform[0].Page2[0].c2_05[1]",
  },
  {
    fieldDefault: "",
    fieldFlags: "25165824",
    fieldMaxLength: "17",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page2[0].AccountNo[0].f2_26[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page2[0].f2_27[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page2[0].f2_28[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page2[0].f2_32[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "0",
    fieldMaxLength: "",
    fieldOptions: ["1", "Off"],
    fieldType: "Button",
    fieldValue: "Off",
    title: "topmostSubform[0].Page2[0].c2_6[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "0",
    fieldMaxLength: "",
    fieldOptions: ["2", "Off"],
    fieldType: "Button",
    fieldValue: "Off",
    title: "topmostSubform[0].Page2[0].c2_6[1]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8392704",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page2[0].f2_33[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page2[0].f2_34[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "25165824",
    fieldMaxLength: "5",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page2[0].f2_35[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page2[0].f2_36[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "25165824",
    fieldMaxLength: "6",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page2[0].f2_37[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page2[0].f2_38[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "25165824",
    fieldMaxLength: "6",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page2[0].f2_39[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page2[0].f2_40[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page2[0].f2_41[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page2[0].f2_42[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "0",
    fieldMaxLength: "11",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page2[0].f2_43[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "0",
    fieldMaxLength: "",
    fieldOptions: ["1", "Off"],
    fieldType: "Button",
    fieldValue: "Off",
    title: "topmostSubform[0].Page2[0].c2_07[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page2[0].f2_44[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page2[0].f2_45[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "8388608",
    fieldMaxLength: "",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page2[0].f2_46[0]",
  },
  {
    fieldDefault: "",
    fieldFlags: "0",
    fieldMaxLength: "10",
    fieldOptions: [],
    fieldType: "Text",
    fieldValue: "",
    title: "topmostSubform[0].Page2[0].f2_47[0]",
  },
];
export const fdfTemplate = {
  "topmostSubform[0].Page1[0].FilingStatus[0].c1_01[0]": "Off",
  "topmostSubform[0].Page1[0].FilingStatus[0].c1_01[1]": "Off",
  "topmostSubform[0].Page1[0].FilingStatus[0].c1_01[2]": "Off",
  "topmostSubform[0].Page1[0].FilingStatus[0].c1_01[3]": "Off",
  "topmostSubform[0].Page1[0].FilingStatus[0].c1_01[4]": "Off",
  "topmostSubform[0].Page1[0].FilingStatus[0].f1_01[0]": "",
  "topmostSubform[0].Page1[0].f1_02[0]": "",
  "topmostSubform[0].Page1[0].f1_03[0]": "",
  "topmostSubform[0].Page1[0].YourSocial[0].f1_04[0]": "",
  "topmostSubform[0].Page1[0].f1_05[0]": "",
  "topmostSubform[0].Page1[0].f1_06[0]": "",
  "topmostSubform[0].Page1[0].SpousesSocial[0].f1_07[0]": "",
  "topmostSubform[0].Page1[0].Address[0].f1_08[0]": "",
  "topmostSubform[0].Page1[0].Address[0].f1_09[0]": "",
  "topmostSubform[0].Page1[0].Address[0].f1_10[0]": "",
  "topmostSubform[0].Page1[0].Address[0].f1_11[0]": "",
  "topmostSubform[0].Page1[0].Address[0].f1_12[0]": "",
  "topmostSubform[0].Page1[0].Address[0].f1_13[0]": "",
  "topmostSubform[0].Page1[0].Address[0].f1_14[0]": "",
  "topmostSubform[0].Page1[0].Address[0].f1_15[0]": "",
  "topmostSubform[0].Page1[0].c1_02[0]": "Off",
  "topmostSubform[0].Page1[0].c1_03[0]": "Off",
  "topmostSubform[0].Page1[0].c1_04[0]": "Off",
  "topmostSubform[0].Page1[0].c1_04[1]": "Off",
  "topmostSubform[0].Page1[0].c1_05[0]": "Off",
  "topmostSubform[0].Page1[0].c1_06[0]": "Off",
  "topmostSubform[0].Page1[0].c1_07[0]": "Off",
  "topmostSubform[0].Page1[0].c1_08[0]": "Off",
  "topmostSubform[0].Page1[0].c1_09[0]": "Off",
  "topmostSubform[0].Page1[0].c1_10[0]": "Off",
  "topmostSubform[0].Page1[0].c1_11[0]": "Off",
  "topmostSubform[0].Page1[0].Dependents_ReadOrder[0].c1_12[0]": "Off",
  "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow1[0].f1_16[0]": "",
  "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow1[0].f1_17[0]": "",
  "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow1[0].f1_18[0]": "",
  "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow1[0].c1_13[0]": "Off",
  "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow1[0].c1_14[0]": "Off",
  "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow2[0].f1_19[0]": "",
  "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow2[0].f1_20[0]": "",
  "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow2[0].f1_21[0]": "",
  "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow2[0].c1_15[0]": "Off",
  "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow2[0].c1_16[0]": "Off",
  "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow3[0].f1_22[0]": "",
  "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow3[0].f1_23[0]": "",
  "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow3[0].f1_24[0]": "",
  "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow3[0].c1_17[0]": "Off",
  "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow3[0].c1_18[0]": "Off",
  "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow4[0].f1_25[0]": "",
  "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow4[0].f1_26[0]": "",
  "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow4[0].f1_27[0]": "",
  "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow4[0].c1_19[0]": "Off",
  "topmostSubform[0].Page1[0].Table_Dependents[0].BodyRow4[0].c1_20[0]": "Off",
  "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_28[0]": "",
  "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_29[0]": "",
  "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_30[0]": "",
  "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_31[0]": "",
  "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_32[0]": "",
  "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_33[0]": "",
  "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_34[0]": "",
  "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_35[0]": "",
  "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_36[0]": "",
  "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_37[0]": "",
  "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_38[0]": "",
  "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].c1_21[0]": "Off",
  "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_39[0]": "",
  "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_40[0]": "",
  "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_41[0]": "",
  "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].Line10-12_ReadOrder[0].f1_42[0]":
    "",
  "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].Line10-12_ReadOrder[0].f1_43[0]":
    "",
  "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_44[0]": "",
  "topmostSubform[0].Page1[0].Lines1-11_ReadOrder[0].f1_45[0]": "",
  "topmostSubform[0].Page1[0].f1_46[0]": "",
  "topmostSubform[0].Page1[0].f1_47[0]": "",
  "topmostSubform[0].Page1[0].f1_48[0]": "",
  "topmostSubform[0].Page1[0].f1_49[0]": "",
  "topmostSubform[0].Page2[0].c2_01[0]": "Off",
  "topmostSubform[0].Page2[0].c2_02[0]": "Off",
  "topmostSubform[0].Page2[0].c2_03[0]": "Off",
  "topmostSubform[0].Page2[0].f2_01[0]": "",
  "topmostSubform[0].Page2[0].f2_02[0]": "",
  "topmostSubform[0].Page2[0].f2_03[0]": "",
  "topmostSubform[0].Page2[0].f2_04[0]": "",
  "topmostSubform[0].Page2[0].f2_05[0]": "",
  "topmostSubform[0].Page2[0].f2_06[0]": "",
  "topmostSubform[0].Page2[0].f2_07[0]": "",
  "topmostSubform[0].Page2[0].f2_08[0]": "",
  "topmostSubform[0].Page2[0].f2_09[0]": "",
  "topmostSubform[0].Page2[0].f2_10[0]": "",
  "topmostSubform[0].Page2[0].Line25_ReadOrder[0].f2_11[0]": "",
  "topmostSubform[0].Page2[0].Line25_ReadOrder[0].f2_12[0]": "",
  "topmostSubform[0].Page2[0].Line25_ReadOrder[0].f2_13[0]": "",
  "topmostSubform[0].Page2[0].Lines26-27_ReadOrder[0].f2_14[0]": "",
  "topmostSubform[0].Page2[0].Lines26-27_ReadOrder[0].f2_15[0]": "",
  "topmostSubform[0].Page2[0].Lines27-32_ReadOrder[0].f2_16[0]": "",
  "topmostSubform[0].Page2[0].Lines27-32_ReadOrder[0].f2_17[0]": "",
  "topmostSubform[0].Page2[0].Lines27-32_ReadOrder[0].f2_18[0]": "",
  "topmostSubform[0].Page2[0].Lines27-32_ReadOrder[0].f2_19[0]": "",
  "topmostSubform[0].Page2[0].Lines27-32_ReadOrder[0].f2_20[0]": "",
  "topmostSubform[0].Page2[0].Line32-33_ReadOrder[0].f2_21[0]": "",
  "topmostSubform[0].Page2[0].f2_22[0]": "",
  "topmostSubform[0].Page2[0].f2_23[0]": "",
  "topmostSubform[0].Page2[0].c2_04[0]": "Off",
  "topmostSubform[0].Page2[0].f2_24[0]": "",
  "topmostSubform[0].Page2[0].RoutingNo[0].f2_25[0]": "",
  "topmostSubform[0].Page2[0].c2_05[0]": "Off",
  "topmostSubform[0].Page2[0].c2_05[1]": "Off",
  "topmostSubform[0].Page2[0].AccountNo[0].f2_26[0]": "",
  "topmostSubform[0].Page2[0].f2_27[0]": "",
  "topmostSubform[0].Page2[0].f2_28[0]": "",
  "topmostSubform[0].Page2[0].f2_32[0]": "",
  "topmostSubform[0].Page2[0].c2_6[0]": "Off",
  "topmostSubform[0].Page2[0].c2_6[1]": "Off",
  "topmostSubform[0].Page2[0].f2_33[0]": "",
  "topmostSubform[0].Page2[0].f2_34[0]": "",
  "topmostSubform[0].Page2[0].f2_35[0]": "",
  "topmostSubform[0].Page2[0].f2_36[0]": "",
  "topmostSubform[0].Page2[0].f2_37[0]": "",
  "topmostSubform[0].Page2[0].f2_38[0]": "",
  "topmostSubform[0].Page2[0].f2_39[0]": "",
  "topmostSubform[0].Page2[0].f2_40[0]": "",
  "topmostSubform[0].Page2[0].f2_41[0]": "",
  "topmostSubform[0].Page2[0].f2_42[0]": "",
  "topmostSubform[0].Page2[0].f2_43[0]": "",
  "topmostSubform[0].Page2[0].c2_07[0]": "Off",
  "topmostSubform[0].Page2[0].f2_44[0]": "",
  "topmostSubform[0].Page2[0].f2_45[0]": "",
  "topmostSubform[0].Page2[0].f2_46[0]": "",
  "topmostSubform[0].Page2[0].f2_47[0]": "",
};
